// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYxiToO_aHkmAw3_JKrnsFZk_qpyrzRtI',
    appId: '1:183532005850:web:27d19d6c2bd540d600f8e3',
    messagingSenderId: '183532005850',
    projectId: 'lati-games',
    authDomain: 'lati-games.firebaseapp.com',
    storageBucket: 'lati-games.appspot.com',
    measurementId: 'G-30R6XKQHTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrRje_WePSDQQ3WoycS07aIe0nHUCNIoU',
    appId: '1:183532005850:android:49b6a2ed02dcd94800f8e3',
    messagingSenderId: '183532005850',
    projectId: 'lati-games',
    storageBucket: 'lati-games.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9SgARzfG7gz5kRX0Dov2lkQ74HF7zifU',
    appId: '1:183532005850:ios:f1c7ebf61bfa623800f8e3',
    messagingSenderId: '183532005850',
    projectId: 'lati-games',
    storageBucket: 'lati-games.appspot.com',
    iosBundleId: 'com.example.latimovies',
  );
}
